name: Bug Report
description: Report a bug or issue with Vita Agents
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - yasir2000
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! 
        Please provide detailed information to help us reproduce and fix the issue.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug are you reporting?
      options:
        - Crash/Exception
        - Performance Issue
        - Data Corruption/Loss
        - Authentication/Authorization
        - FHIR Processing Error
        - API Error
        - Web Portal Issue
        - CLI Issue
        - Docker/Container Issue
        - Installation/Setup Issue
        - Documentation Error
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this bug?
      options:
        - FHIR Agent
        - Enhanced FHIR Agent (Multi-engine)
        - HL7 Agent
        - EHR Agent
        - Clinical Decision Support
        - Data Harmonization
        - Compliance & Security
        - NLP Agent
        - Web Portal
        - CLI Interface
        - Docker Integration
        - API
        - Authentication
        - Database
        - Monitoring
        - Other
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable, data loss, security issue)
        - High (Major functionality broken, workaround exists)
        - Medium (Functionality impaired, minor workaround exists)
        - Low (Cosmetic issue, functionality works)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Detailed steps to reproduce the behavior:
      placeholder: |
        1. Go to '...'
        2. Configure '...'
        3. Execute '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs/Stack Trace
      description: |
        If applicable, add the full error message, stack trace, or relevant log entries.
        Please format code blocks with triple backticks (```).
      placeholder: |
        ```
        Paste error logs/stack trace here
        ```
      render: shell
    validations:
      required: false

  - type: input
    id: vita-agents-version
    attributes:
      label: Vita Agents Version
      description: What version of Vita Agents are you using?
      placeholder: e.g., v2.1.0, latest, commit hash
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install Vita Agents?
      options:
        - Docker Compose
        - Docker (manual)
        - pip install
        - git clone + pip install -e
        - Source code download
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      placeholder: e.g., 3.11.5, 3.10.12
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Ubuntu 22.04, Windows 11, macOS 13.0
    validations:
      required: true

  - type: dropdown
    id: fhir-engine
    attributes:
      label: FHIR Engine (if applicable)
      description: Which FHIR engine were you using when the bug occurred?
      options:
        - HAPI FHIR
        - IBM FHIR Server
        - Medplum
        - Firely .NET SDK
        - Spark FHIR Server
        - LinuxForHealth FHIR
        - Aidbox
        - Microsoft FHIR Server
        - Google Cloud Healthcare API
        - Amazon HealthLake
        - Custom/Other
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Relevant configuration details (remove sensitive information like passwords, API keys, etc.)
        Include environment variables, config files, CLI arguments, etc.
      placeholder: |
        Environment variables:
        - VITA_FHIR_ENGINE=hapi
        - VITA_LOG_LEVEL=DEBUG
        
        Configuration files:
        ```yaml
        # config.yml content (sanitized)
        ```
      render: yaml
    validations:
      required: false

  - type: textarea
    id: data-sample
    attributes:
      label: Sample Data (if applicable)
      description: |
        If the bug involves data processing, provide a minimal sample of the data that causes the issue.
        Please sanitize any sensitive information (PHI, PII, etc.).
      placeholder: |
        ```json
        {
          "resourceType": "Patient",
          "id": "example",
          "name": [{"family": "Doe", "given": ["John"]}]
        }
        ```
      render: json
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: |
        If you found a workaround for this issue, please describe it.
        This can help other users experiencing the same problem.
      placeholder: Describe any workaround you found...
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: |
        How does this bug affect your work or use case?
        What functionality is blocked or impaired?
      placeholder: |
        This bug prevents me from...
        It affects my workflow by...
        The business impact is...
    validations:
      required: false

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always (100% of the time)
        - Often (>75% of the time)
        - Sometimes (25-75% of the time)
        - Rarely (<25% of the time)
        - Once (happened only once)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        Screenshots, network traces, related issues, etc.
        You can drag and drop images here.
      placeholder: Any additional information, screenshots, or context...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I have removed or sanitized any sensitive information (passwords, API keys, PHI, etc.)
          required: true
        - label: I can reproduce this issue consistently
          required: false

